[package]
name = "download_pdfs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
csv = "1.3.1"
reqwest = {version = "0.11", features = ["blocking"]}
